language: python
sudo: false
cache: 
  directories:
    - buildout-cache
python: 2.7
env:
  - PLONE_VERSION=4.3 QA=true
install:
  - sed -ie "s#travis-4.x.cfg#travis-$PLONE_VERSION.x.cfg#" travis.cfg
  - sed -ie "s#versions-$PLONE_VERSION.x#versions#" travis.cfg
  - mkdir -p buildout-cache/downloads
  - pip install zc.buildout
  - buildout -c travis.cfg annotate
  - buildout -c travis.cfg -N
  - ls bin
script: bin/code-analysis && bin/test
after_success:
  - test $QA && bin/coverage.sh && pip install -q coveralls && coveralls || true
